[HOPSWORKS-3009] Increase memory
logicalclocks/hive-chef pull request #99
Opened 2022-08-15 07:56 UTC by kennethmhc

2022-08-26 10:07 UTC, o-alex approved these changes

2022-09-01 22:11 UTC, SirOibaf requested changes

2022-09-01 22:11 UTC, SirOibaf commented on templates/default/hive-env.sh.erb
> +export HADOOP_HEAPSIZE=5120
We should make this value configurable and not hardcoded.

2022-09-10 18:13 UTC, SirOibaf commented
Closing this as the work was moved here: https://github.com/logicalclocks/hive-chef/pull/100

2022-09-10 18:13 UTC, closed without merging